name = "edge-rag-system"
type = "javascript"
account_id = "your_account_id"
workers_dev = true
compatibility_date = "2024-04-27"

[[bindings]]
type = "vectorize"
name = "VECTORSTORE"
index = "documents"

[[bindings]]
type = "kv_namespace"
name = "CACHE"
namespace_id = "your_kv_namespace_id"

[[bindings]]
type = "d1_database"
name = "DB"
database_name = "rag_system"

[[bindings]]
type = "r2_bucket"
name = "STORAGE"
bucket_name = "rag-storage"

[[bindings]]
type = "vars"
name = "ENVIRONMENT"
text = "development"

[[bindings]]
type = "ai"
name = "AI"
model = "@cf/mistral/mixtral-8x7b-instruct-v0.1"