name = "edge-rag-system"
type = "javascript"
account_id = "57d898b95eafc96b1aabfcb389759c23"
workers_dev = true
compatibility_date = "2024-04-27"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "rag_system"
database_id = "rag_system"

[[vectorize]]
binding = "VECTORSTORE"
index_name = "rag_system"
dimension = 768

[[kv_namespaces]]
binding = "CACHE"
id = "rag_system"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "rag-system"

[vars]
ENVIRONMENT = "development"
MOCK_VECTORIZE = "true"