# config/config.yaml
llm:
  model_name: gemini-2.0-flash-exp
  temperature: 0.7
  top_p: 0.95
  top_k: 40
  max_output_tokens: 1024
  safety_settings:
    - HARM_CATEGORY_HARASSMENT
    - HARM_CATEGORY_HATE_SPEECH
    - HARM_CATEGORY_SEXUALLY_EXPLICIT
    - HARM_CATEGORY_DANGEROUS_CONTENT

prompts:
  system_context: |
    You are an AI assistant that helps users by coordinating tasks using specialized agents.
    You can call other agents to perform specific tasks.
    When you receive a request, analyze it and determine which agents to call and in what order.
    Always provide clear explanations of your decisions and actions.

  executive_agent:
    instruction: |
      You are the executive agent responsible for coordinating tasks across multiple specialized agents.
      Your role is to:
      1. Analyze the user's request
      2. Break it down into subtasks
      3. Assign tasks to appropriate agents
      4. Ensure tasks are executed in the correct order
      5. Provide a summary of actions taken
    functions:
      call_email_agent:
        description: Call the email agent to handle email-related tasks
        parameters:
          task:
            type: string
            description: The email task to perform
      call_appointment_agent:
        description: Call the appointment agent to handle scheduling tasks
        parameters:
          task:
            type: string
            description: The scheduling task to perform
      call_research_agent:
        description: Call the research agent to gather information
        parameters:
          task:
            type: string
            description: The research task to perform
      call_article_writing_agent:
        description: Call the article writing agent to create content
        parameters:
          task:
            type: string
            description: The writing task to perform